(ns Aurinko.slfun
  (:require (Aurinko [skiplist :as sl]))
  (:use clojure.test
        [clojure.java.io :only [file]]))

(defn -main [& args]
  (let [list (sl/new "skiplist" 3 2)]
    (sl/kv list 4 41)
    (sl/kv list 7 70)
    (sl/kv list 4 43)
    (sl/kv list 4 44)
    (sl/kv list 10 100)
    (sl/kv list 1 10)
    (sl/kv list 2 20)
    (sl/kv list 1 11)
    (sl/kv list 2 21)
    (sl/kv list 2 22)
    (sl/kv list 4 42)
    (sl/kv list 3 30)
    (sl/kv list 8 80)
    (sl/kv list 9 90)
    (sl/kv list 4 40)
    (sl/kv list 5 50)
    (sl/kv list 6 60)
    (sl/kv list 3 31)
    (sl/kv list 3 32)
    (sl/kv list 3 33)
    (prn (sl/k list 1))
    (prn (sl/k list 2))
    (prn (sl/k list 3))
    (prn (sl/k list 4))
    (prn (sl/k list 5))
    (prn (sl/k list 6))
    (prn (sl/k list 7))
    (prn (sl/k list 8))
    (prn (sl/k list 9))
    (prn (sl/k list 10))))